name: provider_demo
description: "Provider Demo"
# Example of Counter App Using Provider for state management
# Each Widget is Stateless and is in a separate class and file
# Implements a Clean Architecture with separation of layers
# Uses Bridges to implement the separation of layers
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
